ALTER TABLE `StudentProfile`
  MODIFY `caseStage` ENUM(
    'CONSULTATION_AND_DOCUMENTATION',
    'RESEARCH_PROPOSAL',
    'ENROLMENT_PROCESS',
    'CONDITIONAL_OFFER_LETTER',
    'UNCONDITIONAL_OFFER_LETTER',
    'AWAITING_TUITION_PAYMENT',
    'TUITION_FEE_AND_OSHC_PAID',
    'COE_RECEIVED',
    'GTE_PROCESS',
    'VISA_DRAFT_PREPARATION',
    'VISA_LODGMENT',
    'VISA_GRANTED',
    'VISA_REFUSED',
    'AAT_CASE',
    'WITHDRAWN'
  ) NOT NULL DEFAULT 'CONSULTATION_AND_DOCUMENTATION';

ALTER TABLE `VisaCase`
  MODIFY `caseStage` ENUM(
    'CONSULTATION_AND_DOCUMENTATION',
    'RESEARCH_PROPOSAL',
    'ENROLMENT_PROCESS',
    'CONDITIONAL_OFFER_LETTER',
    'UNCONDITIONAL_OFFER_LETTER',
    'AWAITING_TUITION_PAYMENT',
    'TUITION_FEE_AND_OSHC_PAID',
    'COE_RECEIVED',
    'GTE_PROCESS',
    'VISA_DRAFT_PREPARATION',
    'VISA_LODGMENT',
    'VISA_GRANTED',
    'VISA_REFUSED',
    'AAT_CASE',
    'WITHDRAWN'
  ) NOT NULL DEFAULT 'CONSULTATION_AND_DOCUMENTATION';
