-- Add STUDENT_DELEGATED so assignment handoffs can create bell and email notifications.
ALTER TABLE `WorkflowNotification`
MODIFY COLUMN `type` ENUM(
  'DOCUMENT_RETURNED',
  'DOCUMENT_REVERIFIED',
  'DOCUMENT_RETURN_DISPUTED',
  'DOCUMENT_RETURN_FOLLOW_UP',
  'DOCUMENT_REPLACEMENT_UPLOADED',
  'NEW_STUDENT_APPLICATION',
  'STUDENT_DELEGATED'
) NOT NULL;
